apiVersion: v1
kind: Service
metadata:
  name: medconnect-backend-service
spec:
  type: LoadBalancer # Pour un accès local avec Minikube ou un cluster cloud
  selector:
    app: medconnect-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
